blank_issues_enabled: false
contact_links:
  - name: Questions and Help
    url: https://github.com/dermoumi/crafts/discussions
    about: If you have questions or want to discuss new features and ideas.
